### ISSUE TITLE
IEventQueries. GetSuggestedEvents has a parameter that is not being used in implementing class

### ISSUE THREAD

**Issue by pavlovmilen** [Microsoft/BikeSharing360_BackendServices#5]
Implementing class EventQueries does not filter by userid parameter supplied. Is this intentional?

      
       public IEnumerable<CityEvent> GetSuggestedEvents(int userid)
        {
            return _db.Events
                .Include(e => e.Venue)
                .Include(e => e.Segment)
                .Include(e => e.Genre)
                .Include(e => e.SubGenre)
                .Take(5);
        }
```

**Comment by eiximenis** [comment]
Hi @pavlovmilen 
Thanks for the comment.
Yes, it is "intentional". Originally events should be filtered by user (probably using an R experiment or ML), but finally this functionality was descoped from the Connect() demos. But some code were created using "userid" parameter (and some apps used them). So, finally, we just removed the "userid" filter.

Thanks!

**Comment by pavlovmilen** [comment]
Hi @eiximenis 
Thanks for the update, will close the issue.
